server:
  port: 8081
spring:
  application:
    name: eureka-server
  profiles:
    active: prod
eureka:
  instance:
    hostname: 101.200.228.9
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
