version: '3.3'
services:
  # elasticsearch
  elasticsearch:
    image: elasticsearch:6.5.4
    # docker启动后的名称
    container_name: elasticsearch
    #出现异常自动重启
    restart: always
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    privileged: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200: 9200
      - 9300: 9300