server:
  port: 8083
spring:
  application:
    name: zuul
  profiles:
    active: dev
eureka:
  instance:
    hostname: 127.0.0.1
    instance:
    ##客户端自己告诉服务端多少秒发送一个心跳包
    lease-renewal-interval-in-seconds: 1
    ##客户端告诉服务端等待多少秒之后如果还是没有收到心跳包，那就把我剔除吧
    lease-expiration-duration-in-seconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8081/eureka/
    ###是否需要注册到eureka上
    register-with-eureka: true
    ###需要检索服务
    fetch-registry: true
  server:
    ##是否开启自我保护机制
    enable-self-preservation: false
    ##超过20之后才剔除
    eviction-interval-timer-in-ms: 20000
zuul:
  #网关前缀
  prefix: /api
  routes:
    user-service:
      path: /user/**
    blog-service:
      path: /blog/**
  #统一入口为上面的配置，其他入口忽略
  ignored-patterns: /*-service/**
  # 最大超时10s
  host:
    socket-timeout-millis: 1000
    # 最大连接数
    connect-timeout-millis: 200
  # 需要忽略的服务，用，分隔，配置后不会被路由
  #ignored-services: eurake-client

