server:
  port: 8093
spring:
  profiles:
    active: dev
  application:
    name: mybatis_generator
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.10.101:3306/blog?useUnicode=true&characterEncoding=UTF-8&&useSSL=false
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.lmn.mybatisplus.entity
  mapper-locations: classpath*:mapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true