server:
  port: 8090
spring:
  application:
    name: osgi
  profiles:
    active: dev
eureka:
  instance:
    hostname: 127.0.0.1
    instance:
    ##客户端自己告诉服务端多少秒发送一个心跳包
    lease-renewal-interval-in-seconds: 1
    ##客户端告诉服务端等待多少秒之后如果还是没有收到心跳包，那就把我剔除吧
    lease-expiration-duration-in-seconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8081/eureka/
    ###是否需要注册到eureka上
    register-with-eureka: true
    ###需要检索服务
    fetch-registry: true
  server:
    ##是否开启自我保护机制
    enable-self-preservation: false
    ##超过20之后才剔除
    eviction-interval-timer-in-ms: 20000
